// Migration redirect map: turns compare_results (old URLs that are now missing
// or broken) into deployable redirect files, suggesting targets from the current
// crawl by slug/title token overlap. Pure Node — usable from IPC, MCP and tests.
import type Database from 'better-sqlite3';

export type Confidence = 'high' | 'medium' | 'none';

export interface RedirectEntry {
  oldUrl: string;
  oldPath: string;
  target: string | null;
  confidence: Confidence;
  score: number;
  reason: string;
}

function tokens(s: string): Set<string> {
  return new Set(
    s
      .toLowerCase()
      .replace(/\.(html?|php|aspx?)$/i, '')
      .split(/[^a-z0-9]+/)
      .filter((t) => t.length > 1)
  );
}

function lastSegment(path: string): string {
  const parts = path.split('?')[0].split('/').filter(Boolean);
  return parts[parts.length - 1] ?? '';
}

function jaccard(a: Set<string>, b: Set<string>): number {
  if (a.size === 0 || b.size === 0) return 0;
  let inter = 0;
  for (const t of a) if (b.has(t)) inter++;
  return inter / (a.size + b.size - inter);
}

interface Candidate {
  url: string;
  slugTokens: Set<string>;
  titleTokens: Set<string>;
}

/** Suggest redirect targets for every old URL the comparison flagged as missing/broken. */
export function buildRedirectEntries(db: Database.Database): RedirectEntry[] {
  const rows = db
    .prepare(
      `SELECT old_url, old_title, result FROM compare_results
       WHERE result IN ('missing', 'broken') ORDER BY old_url`
    )
    .all() as { old_url: string; old_title: string | null; result: string }[];
  if (rows.length === 0) return [];

  const candidates: Candidate[] = (
    db
      .prepare(
        `SELECT url, title FROM pages
         WHERE is_internal = 1 AND fetched = 1 AND status = 200
           AND content_type LIKE '%html%' AND indexable = 1`
      )
      .all() as { url: string; title: string | null }[]
  ).map((p) => {
    let slug = '';
    try {
      slug = lastSegment(new URL(p.url).pathname);
    } catch {
      slug = '';
    }
    return { url: p.url, slugTokens: tokens(slug), titleTokens: tokens(p.title ?? '') };
  });

  const entries: RedirectEntry[] = [];
  for (const r of rows) {
    let oldPath = r.old_url;
    try {
      const u = new URL(r.old_url);
      oldPath = u.pathname + u.search;
    } catch {
      // keep raw
    }
    const oldSlug = tokens(lastSegment(oldPath));
    const oldTitle = tokens(r.old_title ?? '');

    let best: { url: string; score: number } | null = null;
    for (const c of candidates) {
      // Slug similarity dominates; title similarity assists when present.
      const score =
        jaccard(oldSlug, c.slugTokens) * 0.7 +
        (oldTitle.size > 0 ? jaccard(oldTitle, c.titleTokens) * 0.3 : 0);
      if (score > 0 && (!best || score > best.score)) best = { url: c.url, score };
    }

    const score = best ? Math.round(best.score * 100) / 100 : 0;
    const confidence: Confidence = score >= 0.6 ? 'high' : score >= 0.3 ? 'medium' : 'none';
    entries.push({
      oldUrl: r.old_url,
      oldPath,
      target: confidence === 'none' ? null : best!.url,
      confidence,
      score,
      reason: r.result,
    });
  }
  return entries;
}

// ---------------------------------------------------------------------------
// Renderers. Entries without a target ship as comments so nothing deploys blind.
// ---------------------------------------------------------------------------
export function renderHtaccess(entries: RedirectEntry[]): string {
  const lines = [
    '# 301 redirect map generated by Pulse SEO',
    '# Review medium-confidence lines; "none" entries need a manual target.',
    '',
  ];
  for (const e of entries) {
    if (e.target) {
      lines.push(
        `${e.confidence === 'medium' ? '# REVIEW (medium confidence)\n' : ''}Redirect 301 ${e.oldPath.split('?')[0]} ${e.target}`
      );
    } else {
      lines.push(`# TODO no target found: ${e.oldPath}`);
    }
  }
  return lines.join('\n') + '\n';
}

export function renderNginx(entries: RedirectEntry[]): string {
  const lines = [
    '# 301 redirect map generated by Pulse SEO (server block context)',
    '',
  ];
  for (const e of entries) {
    if (e.target) {
      lines.push(
        `${e.confidence === 'medium' ? '# REVIEW (medium confidence)\n' : ''}location = ${e.oldPath.split('?')[0]} { return 301 ${e.target}; }`
      );
    } else {
      lines.push(`# TODO no target found: ${e.oldPath}`);
    }
  }
  return lines.join('\n') + '\n';
}

/** CSV importable by the WordPress "Redirection" plugin (source,target). */
export function renderWpCsv(entries: RedirectEntry[]): string {
  const esc = (s: string): string => (/[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s);
  const lines = ['source,target'];
  for (const e of entries) {
    if (e.target) lines.push(`${esc(e.oldPath.split('?')[0])},${esc(e.target)}`);
  }
  return lines.join('\n') + '\n';
}

export const REDIRECT_FORMATS = {
  htaccess: { name: 'redirects.htaccess', render: renderHtaccess },
  nginx: { name: 'redirects.nginx.conf', render: renderNginx },
  'wp-csv': { name: 'redirects-wp.csv', render: renderWpCsv },
} as const;

export type RedirectFormat = keyof typeof REDIRECT_FORMATS;
